### ISSUE TITLE
Support new download command

### ISSUE THREAD

**Issue by spencergilbert** [spencergilbert/asdf-k3d#1]

**Comment by MPV** [comment]
Is this why this plugin doesn't seem to be able to install new versions at the moment?

```shell
$ asdf list all k3d | wc -l
0
$ asdf list all k3d
$ echo $?
0
```

**Comment by spencergilbert** [comment]
@MPV no should be unrelated - there's a new download command for asdf but there's compatibility. Mind opening a separate issue for the bug and I'll investigate

**Comment by MPV** [comment]
> @MPV no should be unrelated - there's a new download command for asdf but there's compatibility. Mind opening a separate issue for the bug and I'll investigate

Yep, #3. Thanks.
