### ISSUE TITLE
Raspberry pi.

### ISSUE THREAD

**Issue by andresfgonz** [spencergilbert/asdf-k3d#29]
**Is your feature request related to a problem? Please describe.**

This plugin does not work in My raspberry pi 4. after try "asdf install k3d latest/anyone" it says Architecture not supported. but when I use the official release form k3d.io it works.

I'm running a ubuntu server 22.04 LTS

**Comment by spencergilbert** [comment]
Hey, thanks for reporting - can your share the output from `uname -s` and `uname -m` from the server?

**Comment by spencergilbert** [comment]
I'll take a look at this today and see if I can reproduce/resolve. Thanks for the details!

**Comment by spencergilbert** [comment]
Ah, so the installer has been looking for `arm64` so it doesn't match `aarch64` this should be an easy fix.

**Comment by spencergilbert** [comment]
@wataruian @andresfgonz the newest version should correctly download the arm64 binary for `k3d` now, let me know if you're still seeing an issue.
