### ISSUE TITLE
Not able to find versions to install

### ISSUE THREAD

**Issue by MPV** [spencergilbert/asdf-k3d#3]
This plugin doesn't seem to be able to find (thus install?) new versions at the moment?

```shell
$ asdf list all k3d | wc -l
0
$ asdf list all k3d
$ echo $?
0
```

**Comment by spencergilbert** [comment]
:thinking: Was this from a current install? I just tested from a clean environment and don't see a problem

```sh
~/C/s/asdf-k3d on  master
❯ asdf plugin-add k3d

~/C/s/asdf-k3d on  master
❯ asdf list-all k3d
1.5.1
1.6.0
...
3.1.4
3.1.5

~/C/s/asdf-k3d on  master
❯ asdf list all k3d
1.5.1
1.6.0
...
3.1.4
3.1.5
```

**Comment by MPV** [comment]
Yes, from a new install 1-2 days ago.

**Comment by spencergilbert** [comment]
@MPV do you get results if you run `curl -s https://api.github.com/repos/rancher/k3d/releases`?
